//! Single-line text-entry widget. Pill-shaped with AA edges, wave-animated blinkey cursor, text scrolling, focus glow, and selection.
//!
//! Patterns lifted from photon's text_editing.rs + compositing.rs — `chars + widths + cursor` model, pill shape via squircle crossings, wave blinkey with alternating top/bottom brightness, symmetric scroll margins, 4-directional glow blur, XOR selection inversion.

use alloc::string::String;
use alloc::vec::Vec;
use crate::coord::Coord;
use crate::paint::{self, Clip};
use crate::region::Region;
use crate::text::TextRenderer;
use crate::theme;

pub struct Textbox {
    /// Text content as a `Vec<char>` — character-indexed cursor + width arrays.
    pub chars: Vec<char>,
    /// Insertion point in `[0, chars.len()]`.
    pub cursor: usize,
    pub focused: bool,
    /// Cursor is hovering over the textbox bbox. Drives the hover fill colour.
    pub hovered: bool,
    /// Border/stroke thickness in RU (multiplied by `font_size` to get pixels). `0.0` → 1px minimum via the photon `+ 1` idiom — there's always a stroke. The stroke eats inward from the outer pill silhouette, so the textbox's outer bbox stays fixed and the inner usable area shrinks by `2 × stroke_px` in each dimension.
    pub stroke_ru: f32,
    /// Pixel rect (center-anchored).
    pub center_x: Coord,
    pub center_y: Coord,
    pub width: Coord,
    pub height: Coord,
    /// Font size in pixels.
    pub font_size: Coord,
    /// Per-char pixel widths cached after the last edit.
    widths: Vec<Coord>,
    font: &'static str,

    // --- Scroll ---
    /// Horizontal scroll offset in pixels. Positive = text shifted right (cursor near left edge).
    pub scroll_offset: Coord,

    // --- Blinkey ---
    /// Whether the blinkey is currently drawn (visible half of blink cycle).
    pub blinkey_visible: bool,
    /// Which wave variant is drawn: true = top-bright, false = bottom-bright.
    pub blinkey_wave_top: bool,

    // --- Selection ---
    /// If Some, the anchor index where the selection started (shift+click or shift+arrow).
    pub selection_anchor: Option<usize>,

    // --- Mask ---
    /// Alpha mask generated by `draw_textbox_pill`. Sized to `buf_w * buf_h` on first render. 0 = outside textbox, 255 = interior, AA values on edges. Used by glow, text clipping, blinkey bounds.
    mask: Vec<u8>,
    mask_w: usize,
    mask_h: usize,

}

impl Textbox {
    pub fn new(center_x: Coord, center_y: Coord, width: Coord, height: Coord, font_size: Coord) -> Self {
        Self {
            chars: Vec::new(),
            cursor: 0,
            focused: false,
            hovered: false,
            stroke_ru: 0.0,   // → 1 px minimum via the +1 idiom in render_content_into
            center_x,
            center_y,
            width,
            height,
            font_size,
            widths: Vec::new(),
            font: "Open Sans",
            scroll_offset: 0.0,
            blinkey_visible: false,
            blinkey_wave_top: true,
            selection_anchor: None,
            mask: Vec::new(),
            mask_w: 0,
            mask_h: 0,
        }
    }

    /// True if pixel `(x, y)` is inside the textbox rect.
    pub fn contains(&self, x: Coord, y: Coord) -> bool {
        let half_w = self.width * 0.5;
        let half_h = self.height * 0.5;
        x >= self.center_x - half_w && x < self.center_x + half_w
            && y >= self.center_y - half_h && y < self.center_y + half_h
    }

    pub fn set_rect(&mut self, center_x: Coord, center_y: Coord, width: Coord, height: Coord) {
        self.center_x = center_x;
        self.center_y = center_y;
        self.width = width;
        self.height = height;
    }

    pub fn set_font_size(&mut self, font_size: Coord, text: &mut TextRenderer) {
        self.font_size = font_size;
        self.recalc_widths(text);
    }

    fn recalc_widths(&mut self, text: &mut TextRenderer) {
        self.widths.clear();
        self.widths.reserve(self.chars.len());
        let mut buf = [0u8; 4];
        for ch in &self.chars {
            let s = ch.encode_utf8(&mut buf);
            let w = text.measure_text_width(s, self.font_size, 400, self.font);
            self.widths.push(w);
        }
    }

    /// Total text width in pixels.
    fn text_width(&self) -> Coord {
        self.widths.iter().sum()
    }

    /// Pixel x of the leftmost glyph baseline (left inset of pill shape).
    fn text_left(&self) -> Coord {
        self.center_x - self.width * 0.5 + self.padding()
    }

    fn text_right(&self) -> Coord {
        self.center_x + self.width * 0.5 - self.padding()
    }

    fn padding(&self) -> Coord {
        self.font_size * 0.4
    }

    /// Usable text area width (pill interior minus padding on both sides).
    fn usable_width(&self) -> Coord {
        self.width - self.padding() * 2.0
    }

    // --- Editing ---

    pub fn insert_char(&mut self, c: char, text: &mut TextRenderer) {
        if c.is_control() { return; }
        self.delete_selection(text);
        self.chars.insert(self.cursor, c);
        self.cursor += 1;
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn backspace(&mut self, text: &mut TextRenderer) {
        if self.has_selection() { self.delete_selection(text); return; }
        if self.cursor == 0 { return; }
        self.cursor -= 1;
        self.chars.remove(self.cursor);
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn delete_forward(&mut self, text: &mut TextRenderer) {
        if self.has_selection() { self.delete_selection(text); return; }
        if self.cursor >= self.chars.len() { return; }
        self.chars.remove(self.cursor);
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn cursor_left(&mut self) { if self.cursor > 0 { self.cursor -= 1; self.update_scroll(); } }
    pub fn cursor_right(&mut self) { if self.cursor < self.chars.len() { self.cursor += 1; self.update_scroll(); } }
    pub fn cursor_home(&mut self) { self.cursor = 0; self.update_scroll(); }
    pub fn cursor_end(&mut self) { self.cursor = self.chars.len(); self.update_scroll(); }

    // --- Selection ---

    pub fn has_selection(&self) -> bool {
        self.selection_anchor.map_or(false, |a| a != self.cursor)
    }

    /// Get sorted (start, end) of the selection range.
    pub fn selection_range(&self) -> Option<(usize, usize)> {
        self.selection_anchor.and_then(|a| {
            if a == self.cursor { None }
            else { Some((a.min(self.cursor), a.max(self.cursor))) }
        })
    }

    pub fn select_all(&mut self) {
        self.selection_anchor = Some(0);
        self.cursor = self.chars.len();
    }

    pub fn delete_selection(&mut self, text: &mut TextRenderer) {
        if let Some((start, end)) = self.selection_range() {
            self.chars.drain(start..end);
            self.cursor = start;
            self.selection_anchor = None;
            self.recalc_widths(text);
            self.update_scroll();
        }
    }

    /// Get selected text as a String.
    pub fn selected_text(&self) -> Option<String> {
        self.selection_range().map(|(s, e)| self.chars[s..e].iter().collect())
    }

    /// Replace selection (or insert at cursor) with string.
    pub fn insert_str(&mut self, s: &str, text: &mut TextRenderer) {
        self.delete_selection(text);
        for c in s.chars() {
            if !c.is_control() {
                self.chars.insert(self.cursor, c);
                self.cursor += 1;
            }
        }
        self.recalc_widths(text);
        self.update_scroll();
    }

    // --- Scrolling ---

    /// Update scroll offset to keep the cursor visible within symmetric margins.
    fn update_scroll(&mut self) {
        let tw = self.text_width();
        let uw = self.usable_width();
        if tw <= uw {
            self.scroll_offset = 0.0;
            return;
        }
        let margin = uw * 0.05;
        let usable_half = uw * 0.5;
        let text_half = tw * 0.5;

        let max_scroll_right = usable_half - margin - text_half;
        let max_scroll_left = text_half - usable_half + margin;
        self.scroll_offset = self.scroll_offset.clamp(max_scroll_right, max_scroll_left);

        let cursor_px: Coord = self.widths[..self.cursor].iter().sum();
        let cursor_in_centered = cursor_px - text_half;
        let cursor_in_view = cursor_in_centered + self.scroll_offset;
        if cursor_in_view < -usable_half + margin {
            self.scroll_offset = -usable_half + margin - cursor_in_centered;
        } else if cursor_in_view > usable_half - margin {
            self.scroll_offset = usable_half - margin - cursor_in_centered;
        }
    }

    // --- Click ---

    pub fn cursor_index_from_x(&self, click_x: Coord) -> usize {
        let text_start = self.text_start_x();
        if click_x <= text_start { return 0; }
        let mut accum = text_start;
        for (i, &w) in self.widths.iter().enumerate() {
            let mid = accum + w * 0.5;
            if click_x < mid { return i; }
            accum += w;
        }
        self.chars.len()
    }

    pub fn handle_click(&mut self, x: Coord, y: Coord) {
        if self.contains(x, y) {
            self.focused = true;
            self.cursor = self.cursor_index_from_x(x);
            self.selection_anchor = None;
            self.blinkey_visible = true;
            self.blinkey_wave_top = true;
        } else {
            self.focused = false;
            self.blinkey_visible = false;
            self.selection_anchor = None;
        }
    }

    // --- Blinkey ---

    /// Flip the blinkey wave between top-bright and bottom-bright. Returns true if the blinkey is visible (caller should redraw).
    pub fn flip_blinkey(&mut self) -> bool {
        if !self.focused { return false; }
        self.blinkey_wave_top = !self.blinkey_wave_top;
        self.blinkey_visible = true;
        true
    }

    // --- Layout helpers ---

    /// Compute the pixel X where text rendering starts, accounting for centering and scroll.
    fn text_start_x(&self) -> Coord {
        let tw = self.text_width();
        let uw = self.usable_width();
        let usable_center = self.center_x;
        if tw <= uw {
            // Text fits — center it in the usable area.
            usable_center - tw * 0.5
        } else {
            // Text overflows — offset by scroll.
            usable_center - tw * 0.5 + self.scroll_offset
        }
    }

    /// Pixel X of the cursor bar.
    fn cursor_pixel_x(&self) -> Coord {
        self.text_start_x() + self.widths[..self.cursor].iter().sum::<Coord>()
    }

    /// Bounding rect (viewport coords) of the cursor's wave smear including the 7-pixel decay on each side. Used to size a sub-viewport `cursor_group` so blink ticks touch ~16 × font_size pixels instead of the entire viewport.
    pub fn cursor_bbox(&self) -> Region {
        let cpx = self.cursor_pixel_x();
        let x = cpx - 8.0;
        let y = self.center_y - self.font_size * 0.5;
        Region::new(x, y, 16.0, self.font_size)
    }

    /// Bounding rect (viewport coords) of the textbox + glow halo. Pads the pill rect by `font_size` on each side so `apply_textbox_glow`'s outward blur has room to fade — without this the glow clips at the bbox edge of the sub-viewport `textbox_group` buffer.
    pub fn bbox(&self) -> Region {
        let glow_pad = self.font_size;
        Region::new(
            self.center_x - self.width  * 0.5 - glow_pad,
            self.center_y - self.height * 0.5 - glow_pad,
            self.width  + 2.0 * glow_pad,
            self.height + 2.0 * glow_pad,
        )
    }

    // --- Rendering ---

    /// Render the textbox interior — hard-edged squircle pill with a stroke ring around it.
    ///
    /// Photon's avatar-ring approach: compute TWO squircle silhouettes via [`paint::squircle_inset`].
    /// The OUTER silhouette is the full pill at `radius = height/2`. The INNER silhouette is the
    /// same squircle inset by `stroke_px` on every side (`radius - stroke_px`, bbox shrunk by
    /// `2·stroke_px` in each dimension). Pixels between outer and inner = stroke colour
    /// (`theme::TEXTBOX_LIGHT_EDGE`); pixels inside inner = state-based fill:
    ///   - focused (active):  `theme::TEXTBOX_ACTIVE`
    ///   - hovered only:      `theme::TEXTBOX_HOVER`
    ///   - default:           `theme::TEXTBOX_FILL`
    ///
    /// Stroke thickness: `stroke_px = (stroke_ru × font_size + 1.0) as isize`. The `+ 1` enforces a
    /// 1-px minimum when `stroke_ru == 0` (photon's "add one for minimum" idiom). Stroke eats
    /// inward — outer pill bbox stays fixed, inner usable area shrinks.
    ///
    /// No AA on either silhouette — each pixel is binary in/out, decided per row by comparing
    /// the column against the squircle inset for that row. Squirdleyness = 3 for both rings.
    ///
    /// Populates `self.mask` (255 inside outer pill, 0 outside) for downstream glow + selection.
    pub fn render_content_into(
        &mut self,
        pixels: &mut [u32],
        buf_w: usize,
        buf_h: usize,
        offset_x: Coord,
        offset_y: Coord,
        _text: &mut TextRenderer,
        _clip: Option<Clip>,
        _mask: Option<&paint::AlphaMask>,
    ) {
        let bw = self.width as isize;
        let bh = self.height as isize;
        let pill_x_l = (self.center_x - self.width * 0.5 - offset_x) as isize;
        let pill_y_l = (self.center_y - self.height * 0.5 - offset_y) as isize;

        let needed = buf_w * buf_h;
        if self.mask.len() != needed {
            self.mask.resize(needed, 0);
            self.mask_w = buf_w;
            self.mask_h = buf_h;
        } else {
            self.mask.fill(0);
        }

        let fill = if self.focused {
            theme::TEXTBOX_ACTIVE
        } else if self.hovered {
            theme::TEXTBOX_HOVER
        } else {
            theme::TEXTBOX_FILL
        };
        let stroke_color = theme::TEXTBOX_LIGHT_EDGE;

        let stroke_px = (self.stroke_ru * self.font_size + 1.0) as isize;
        let outer_radius = self.height as f32 * 0.5;
        let inner_radius = (outer_radius - stroke_px as f32).max(0.0);
        let squirdleyness = 3i32;

        let cy = pill_y_l + (bh / 2);
        let y0 = pill_y_l.max(0) as usize;
        let y1 = (pill_y_l + bh).min(buf_h as isize).max(0) as usize;

        for row in y0..y1 {
            let dy = (row as isize - cy).abs() as f32;

            // Outer silhouette inset for this row.
            let outer_inset = paint::squircle_inset(dy, outer_radius, squirdleyness) as isize;
            let outer_left_v  = pill_x_l + outer_inset;
            let outer_right_v = pill_x_l + bw - outer_inset;
            if outer_right_v <= outer_left_v { continue; }
            let outer_left  = outer_left_v.max(0) as usize;
            let outer_right = outer_right_v.min(buf_w as isize) as usize;

            // Inner silhouette (the stroke-inset squircle). Only present when this row is within
            // the inner pill's y range AND the inner radius is positive.
            let has_inner = inner_radius > 0.0 && dy <= inner_radius;
            let (inner_left, inner_right) = if has_inner {
                let inner_inset = paint::squircle_inset(dy, inner_radius, squirdleyness) as isize;
                let l = (pill_x_l + stroke_px + inner_inset).max(0) as usize;
                let r = ((pill_x_l + bw - stroke_px - inner_inset).min(buf_w as isize)).max(0) as usize;
                (l, r)
            } else {
                (outer_left, outer_left)   // empty inner range — entire outer row is stroke
            };

            let row_base = row * buf_w;
            for col in outer_left..outer_right {
                let inside_inner = col >= inner_left && col < inner_right;
                pixels[row_base + col] = if inside_inner { fill } else { stroke_color };
                self.mask[row_base + col] = 255;
            }
        }
    }

    /// Paint the focus glow into a buffer using the pill silhouette captured in `self.mask` by the last [`render_content_into`](Self::render_content_into) call. The glow goes into its OWN layer so AlphaOver in the textbox_group's Stack program produces the correct `glow_color × (1 - mask) + pill × mask` blend at AA edges — saturating-adding glow into the content layer would stain the pill's AA pixels with full glow_color.
    pub fn render_glow_into(&self, pixels: &mut [u32], buf_w: usize, buf_h: usize, offset_x: Coord, offset_y: Coord) {
        if !self.focused { return; }
        let bw = self.width as usize;
        let bh = self.height as usize;
        let cy_l = (self.center_y - offset_y) as isize;
        paint::apply_textbox_glow(pixels, &self.mask, buf_w, buf_h, cy_l, bw, bh, theme::GLOW_DEFAULT);
        // `offset_x` reserved for future use; the glow currently centers on the same x-axis as the pill so no x-offset math is required here.
        let _ = offset_x;
    }

    /// Render only the blinkey wave cursor into a buffer (typically a sub-viewport `cursor_group` buffer). `(offset_x, offset_y)` is the buffer's top-left in viewport coords. The buffer should be zeroed before calling — blinkey writes non-zero pixels for additive composition.
    pub fn render_blinkey_into(&self, pixels: &mut [u32], buf_w: usize, buf_h: usize, offset_x: Coord, offset_y: Coord) {
        if !self.focused || self.has_selection() || !self.blinkey_visible { return; }
        let cpx_v = self.cursor_pixel_x();
        let blinkey_x_v = cpx_v as isize;
        let blinkey_x = (blinkey_x_v - offset_x as isize) as usize;
        let blinkey_y = ((self.center_y - self.font_size * 0.5) - offset_y) as usize;
        let blinkey_h = self.font_size as usize;
        if blinkey_x >= 7 && blinkey_x + 7 < buf_w && blinkey_y + blinkey_h <= buf_h {
            paint::draw_blinkey(pixels, buf_w, blinkey_x, blinkey_y, blinkey_h, self.blinkey_wave_top, true);
        }
    }
}
