//! Single-line text-entry widget. Pill-shaped with AA edges, wave-animated blinkey cursor, text scrolling, focus glow, and selection.
//!
//! Patterns lifted from photon's text_editing.rs + compositing.rs — `chars + widths + cursor` model, pill shape via squircle crossings, wave blinkey with alternating top/bottom brightness, symmetric scroll margins, 4-directional glow blur, XOR selection inversion.

use alloc::string::String;
use alloc::vec::Vec;
use crate::coord::Coord;
use crate::paint::{self, Clip};
use crate::region::Region;
use crate::text::TextRenderer;
use crate::theme;

pub struct Textbox {
    /// Text content as a `Vec<char>` — character-indexed cursor + width arrays.
    pub chars: Vec<char>,
    /// Insertion point in `[0, chars.len()]`.
    pub cursor: usize,
    pub focused: bool,
    /// Pixel rect (center-anchored).
    pub center_x: Coord,
    pub center_y: Coord,
    pub width: Coord,
    pub height: Coord,
    /// Font size in pixels.
    pub font_size: Coord,
    /// Per-char pixel widths cached after the last edit.
    widths: Vec<Coord>,
    font: &'static str,

    // --- Scroll ---
    /// Horizontal scroll offset in pixels. Positive = text shifted right (cursor near left edge).
    pub scroll_offset: Coord,

    // --- Blinkey ---
    /// Whether the blinkey is currently drawn (visible half of blink cycle).
    pub blinkey_visible: bool,
    /// Which wave variant is drawn: true = top-bright, false = bottom-bright.
    pub blinkey_wave_top: bool,

    // --- Selection ---
    /// If Some, the anchor index where the selection started (shift+click or shift+arrow).
    pub selection_anchor: Option<usize>,

    // --- Mask ---
    /// Alpha mask generated by `draw_textbox_pill`. Sized to `buf_w * buf_h` on first render. 0 = outside textbox, 255 = interior, AA values on edges. Used by glow, text clipping, blinkey bounds.
    mask: Vec<u8>,
    mask_w: usize,
    mask_h: usize,

    // --- Glow state ---
    /// Whether the glow is currently applied (so we can remove it on defocus).
    glow_applied: bool,
}

impl Textbox {
    pub fn new(center_x: Coord, center_y: Coord, width: Coord, height: Coord, font_size: Coord) -> Self {
        Self {
            chars: Vec::new(),
            cursor: 0,
            focused: false,
            center_x,
            center_y,
            width,
            height,
            font_size,
            widths: Vec::new(),
            font: "Open Sans",
            scroll_offset: 0.0,
            blinkey_visible: false,
            blinkey_wave_top: true,
            selection_anchor: None,
            mask: Vec::new(),
            mask_w: 0,
            mask_h: 0,
            glow_applied: false,
        }
    }

    /// True if pixel `(x, y)` is inside the textbox rect.
    pub fn contains(&self, x: Coord, y: Coord) -> bool {
        let half_w = self.width * 0.5;
        let half_h = self.height * 0.5;
        x >= self.center_x - half_w && x < self.center_x + half_w
            && y >= self.center_y - half_h && y < self.center_y + half_h
    }

    pub fn set_rect(&mut self, center_x: Coord, center_y: Coord, width: Coord, height: Coord) {
        self.center_x = center_x;
        self.center_y = center_y;
        self.width = width;
        self.height = height;
    }

    pub fn set_font_size(&mut self, font_size: Coord, text: &mut TextRenderer) {
        self.font_size = font_size;
        self.recalc_widths(text);
    }

    fn recalc_widths(&mut self, text: &mut TextRenderer) {
        self.widths.clear();
        self.widths.reserve(self.chars.len());
        let mut buf = [0u8; 4];
        for ch in &self.chars {
            let s = ch.encode_utf8(&mut buf);
            let w = text.measure_text_width(s, self.font_size, 400, self.font);
            self.widths.push(w);
        }
    }

    /// Total text width in pixels.
    fn text_width(&self) -> Coord {
        self.widths.iter().sum()
    }

    /// Pixel x of the leftmost glyph baseline (left inset of pill shape).
    fn text_left(&self) -> Coord {
        self.center_x - self.width * 0.5 + self.padding()
    }

    fn text_right(&self) -> Coord {
        self.center_x + self.width * 0.5 - self.padding()
    }

    fn padding(&self) -> Coord {
        self.font_size * 0.4
    }

    /// Usable text area width (pill interior minus padding on both sides).
    fn usable_width(&self) -> Coord {
        self.width - self.padding() * 2.0
    }

    // --- Editing ---

    pub fn insert_char(&mut self, c: char, text: &mut TextRenderer) {
        if c.is_control() { return; }
        self.delete_selection(text);
        self.chars.insert(self.cursor, c);
        self.cursor += 1;
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn backspace(&mut self, text: &mut TextRenderer) {
        if self.has_selection() { self.delete_selection(text); return; }
        if self.cursor == 0 { return; }
        self.cursor -= 1;
        self.chars.remove(self.cursor);
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn delete_forward(&mut self, text: &mut TextRenderer) {
        if self.has_selection() { self.delete_selection(text); return; }
        if self.cursor >= self.chars.len() { return; }
        self.chars.remove(self.cursor);
        self.recalc_widths(text);
        self.update_scroll();
    }

    pub fn cursor_left(&mut self) { if self.cursor > 0 { self.cursor -= 1; self.update_scroll(); } }
    pub fn cursor_right(&mut self) { if self.cursor < self.chars.len() { self.cursor += 1; self.update_scroll(); } }
    pub fn cursor_home(&mut self) { self.cursor = 0; self.update_scroll(); }
    pub fn cursor_end(&mut self) { self.cursor = self.chars.len(); self.update_scroll(); }

    // --- Selection ---

    pub fn has_selection(&self) -> bool {
        self.selection_anchor.map_or(false, |a| a != self.cursor)
    }

    /// Get sorted (start, end) of the selection range.
    pub fn selection_range(&self) -> Option<(usize, usize)> {
        self.selection_anchor.and_then(|a| {
            if a == self.cursor { None }
            else { Some((a.min(self.cursor), a.max(self.cursor))) }
        })
    }

    pub fn select_all(&mut self) {
        self.selection_anchor = Some(0);
        self.cursor = self.chars.len();
    }

    pub fn delete_selection(&mut self, text: &mut TextRenderer) {
        if let Some((start, end)) = self.selection_range() {
            self.chars.drain(start..end);
            self.cursor = start;
            self.selection_anchor = None;
            self.recalc_widths(text);
            self.update_scroll();
        }
    }

    /// Get selected text as a String.
    pub fn selected_text(&self) -> Option<String> {
        self.selection_range().map(|(s, e)| self.chars[s..e].iter().collect())
    }

    /// Replace selection (or insert at cursor) with string.
    pub fn insert_str(&mut self, s: &str, text: &mut TextRenderer) {
        self.delete_selection(text);
        for c in s.chars() {
            if !c.is_control() {
                self.chars.insert(self.cursor, c);
                self.cursor += 1;
            }
        }
        self.recalc_widths(text);
        self.update_scroll();
    }

    // --- Scrolling ---

    /// Update scroll offset to keep the cursor visible within symmetric margins.
    fn update_scroll(&mut self) {
        let tw = self.text_width();
        let uw = self.usable_width();
        if tw <= uw {
            self.scroll_offset = 0.0;
            return;
        }
        let margin = uw * 0.05;
        let usable_half = uw * 0.5;
        let text_half = tw * 0.5;

        let max_scroll_right = usable_half - margin - text_half;
        let max_scroll_left = text_half - usable_half + margin;
        self.scroll_offset = self.scroll_offset.clamp(max_scroll_right, max_scroll_left);

        let cursor_px: Coord = self.widths[..self.cursor].iter().sum();
        let cursor_in_centered = cursor_px - text_half;
        let cursor_in_view = cursor_in_centered + self.scroll_offset;
        if cursor_in_view < -usable_half + margin {
            self.scroll_offset = -usable_half + margin - cursor_in_centered;
        } else if cursor_in_view > usable_half - margin {
            self.scroll_offset = usable_half - margin - cursor_in_centered;
        }
    }

    // --- Click ---

    pub fn cursor_index_from_x(&self, click_x: Coord) -> usize {
        let text_start = self.text_start_x();
        if click_x <= text_start { return 0; }
        let mut accum = text_start;
        for (i, &w) in self.widths.iter().enumerate() {
            let mid = accum + w * 0.5;
            if click_x < mid { return i; }
            accum += w;
        }
        self.chars.len()
    }

    pub fn handle_click(&mut self, x: Coord, y: Coord) {
        if self.contains(x, y) {
            self.focused = true;
            self.cursor = self.cursor_index_from_x(x);
            self.selection_anchor = None;
            self.blinkey_visible = true;
            self.blinkey_wave_top = true;
        } else {
            self.focused = false;
            self.blinkey_visible = false;
            self.selection_anchor = None;
        }
    }

    // --- Blinkey ---

    /// Flip the blinkey wave between top-bright and bottom-bright. Returns true if the blinkey is visible (caller should redraw).
    pub fn flip_blinkey(&mut self) -> bool {
        if !self.focused { return false; }
        self.blinkey_wave_top = !self.blinkey_wave_top;
        self.blinkey_visible = true;
        true
    }

    // --- Layout helpers ---

    /// Compute the pixel X where text rendering starts, accounting for centering and scroll.
    fn text_start_x(&self) -> Coord {
        let tw = self.text_width();
        let uw = self.usable_width();
        let usable_center = self.center_x;
        if tw <= uw {
            // Text fits — center it in the usable area.
            usable_center - tw * 0.5
        } else {
            // Text overflows — offset by scroll.
            usable_center - tw * 0.5 + self.scroll_offset
        }
    }

    /// Pixel X of the cursor bar.
    fn cursor_pixel_x(&self) -> Coord {
        self.text_start_x() + self.widths[..self.cursor].iter().sum::<Coord>()
    }

    /// Bounding rect (viewport coords) of the cursor's wave smear including the 7-pixel decay on each side. Used to size a sub-viewport `cursor_group` so blink ticks touch ~16 × font_size pixels instead of the entire viewport.
    pub fn cursor_bbox(&self) -> Region {
        let cpx = self.cursor_pixel_x();
        let x = cpx - 8.0;
        let y = self.center_y - self.font_size * 0.5;
        Region::new(x, y, 16.0, self.font_size)
    }

    /// Bounding rect (viewport coords) of the textbox's pill — the natural bbox for a `textbox_group`.
    pub fn bbox(&self) -> Region {
        Region::new(self.center_x - self.width * 0.5, self.center_y - self.height * 0.5, self.width, self.height)
    }

    // --- Rendering ---

    /// Render pill + mask + text + selection (NOT the blinkey — that's a separate path so it can live in its own bbox-sized group). `(offset_x, offset_y)` is the buffer's top-left in viewport coords; pass `(0, 0)` for a full-viewport buffer or `(bbox.x, bbox.y)` for a sub-viewport buffer sized to the textbox's [`bbox`](Self::bbox).
    pub fn render(
        &mut self,
        pixels: &mut [u32],
        buf_w: usize,
        buf_h: usize,
        offset_x: Coord,
        offset_y: Coord,
        text: &mut TextRenderer,
        _clip: Option<Clip>,
        _mask: Option<&paint::AlphaMask>,
    ) {
        let bw = self.width as usize;
        let bh = self.height as usize;
        // Local (buffer-relative) center.
        let cx_l = (self.center_x - offset_x) as usize;
        let cy_l = (self.center_y - offset_y) as isize;
        let center_y_l = self.center_y - offset_y;

        let needed = buf_w * buf_h;
        if self.mask.len() != needed {
            self.mask.resize(needed, 0);
            self.mask_w = buf_w;
            self.mask_h = buf_h;
        } else {
            self.mask.fill(0);
        }

        // 1. Pill shape + mask (buffer-local).
        paint::draw_textbox_pill(pixels, &mut self.mask, buf_w, buf_h, cx_l, cy_l, bw, bh);

        // 2. Glow (if focused).
        if self.focused && !self.glow_applied {
            paint::apply_textbox_glow(pixels, &self.mask, buf_w, buf_h, cy_l, bw, bh, true, theme::GLOW_DEFAULT);
            self.glow_applied = true;
        } else if !self.focused && self.glow_applied {
            paint::apply_textbox_glow(pixels, &self.mask, buf_w, buf_h, cy_l, bw, bh, false, theme::GLOW_DEFAULT);
            self.glow_applied = false;
        }

        // 3. Text — buffer-local positions: subtract offset from every viewport coord.
        let s: String = self.chars.iter().collect();
        if !s.is_empty() {
            let text_x_v = self.text_start_x();
            let tb_left_v = self.center_x - self.width * 0.5;
            let tb_right_v = self.center_x + self.width * 0.5;
            let mut x_off = text_x_v;
            let mut char_buf = [0u8; 4];
            for (i, &ch) in self.chars.iter().enumerate() {
                let cw = self.widths[i];
                let char_right = x_off + cw;
                if char_right >= tb_left_v && x_off <= tb_right_v {
                    let cs = ch.encode_utf8(&mut char_buf);
                    let _ = text.draw_text_left_u32(
                        pixels, buf_w, buf_h,
                        cs,
                        x_off - offset_x, center_y_l,
                        self.font_size, 400,
                        theme::TEXT_COLOUR,
                        self.font,
                        None, None, None,
                    );
                }
                x_off += cw;
            }
        }

        // 4. Selection highlight (XOR inversion within textbox mask) — buffer-local.
        if let Some((sel_start, sel_end)) = self.selection_range() {
            let start_px = (self.text_start_x() + self.widths[..sel_start].iter().sum::<Coord>()) - offset_x;
            let end_px = (self.text_start_x() + self.widths[..sel_end].iter().sum::<Coord>()) - offset_x;
            let sel_top = (center_y_l - self.font_size * 0.5) as isize;
            let sel_bot = (center_y_l + self.font_size * 0.5) as isize;
            let tb_left = ((self.center_x - self.width * 0.5) - offset_x) as isize;
            let tb_right = ((self.center_x + self.width * 0.5) - offset_x) as isize;
            for sy in sel_top.max(0)..sel_bot.min(buf_h as isize) {
                for sx in (start_px as isize).max(tb_left)..(end_px as isize).min(tb_right) {
                    if sx >= 0 && (sx as usize) < buf_w {
                        let idx = sy as usize * buf_w + sx as usize;
                        if self.mask[idx] > 0 {
                            pixels[idx] ^= 0x00FFFFFF;
                        }
                    }
                }
            }
        }
    }

    /// Render only the blinkey wave cursor into a buffer (typically a sub-viewport `cursor_group` buffer). `(offset_x, offset_y)` is the buffer's top-left in viewport coords. The buffer should be zeroed before calling — blinkey writes non-zero pixels for additive composition.
    pub fn render_blinkey_into(&self, pixels: &mut [u32], buf_w: usize, buf_h: usize, offset_x: Coord, offset_y: Coord) {
        if !self.focused || self.has_selection() || !self.blinkey_visible { return; }
        let cpx_v = self.cursor_pixel_x();
        let blinkey_x_v = cpx_v as isize;
        let blinkey_x = (blinkey_x_v - offset_x as isize) as usize;
        let blinkey_y = ((self.center_y - self.font_size * 0.5) - offset_y) as usize;
        let blinkey_h = self.font_size as usize;
        if blinkey_x >= 7 && blinkey_x + 7 < buf_w && blinkey_y + blinkey_h < buf_h {
            paint::draw_blinkey(pixels, buf_w, blinkey_x, blinkey_y, blinkey_h, self.blinkey_wave_top, true);
        }
    }
}
